# Generated by Django 4.2 on 2023-12-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(help_text='Unique number identifying the PO', max_length=100, unique=True)),
                ('order_date', models.DateTimeField(help_text='Date when the order was placed')),
                ('delivery_date', models.DateTimeField(help_text='Expected or actual delivery date of the order')),
                ('items', models.JSONField(help_text='Details of items ordered')),
                ('quantity', models.IntegerField(help_text='Total quantity of items in the PO')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], help_text='Current status of the PO', max_length=20)),
                ('quality_rating', models.FloatField(blank=True, help_text='Rating given to the vendor for this PO', null=True)),
                ('issue_date', models.DateTimeField(help_text='Timestamp when the PO was issued to the vendor')),
                ('acknowledgment_date', models.DateTimeField(blank=True, help_text='Timestamp when the vendor acknowledged the PO', null=True)),
                ('vendor', models.ForeignKey(help_text='Link to the Vendor model', on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date of the performance record')),
                ('on_time_delivery_rate', models.FloatField(help_text='Historical record of the on-time delivery rate')),
                ('quality_rating_avg', models.FloatField(help_text='Historical record of the quality rating average')),
                ('average_response_time', models.FloatField(help_text='Historical record of the average response time')),
                ('fulfillment_rate', models.FloatField(help_text='Historical record of the fulfillment rate')),
                ('vendor', models.ForeignKey(help_text='Link to the Vendor model', on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
